### PR TITLE
WIP: KiCad files for LED Strip Driver WeMos D1 Mini Shield

### PR DESCRIPTION
**Pull request by HowManyOliversAreThere**
Working on a set of KiCad files that implements the LED Strip driving concept in a more compact, reliable, and repeatable fashion.

Currently schematic is ready for review (no specific components have been selected, just looking at overall connections and design intent). Things to note:
* Diode on 12V rail for reverse polarity protection, although may interfere with LED driving (and would have to be highly rated)
* FET schematic component will change depending on type of footprint had (123 -> GSD mapping)
* Currently 12V -> 5V module used, could be / may have to be changed to discrete components (will have high current passed through with 3x LED strips)
* Debounce capacitor added to rotary encoder switch

### CODE REVIEW

**Comment by mattytrentini** [comment]
Looking good! About the points you made...

I'm currently using the [IRLB8721](http://www.infineon.com/cms/en/product/power/mosfet/20v-300v-n-channel-power-mosfet/20v-30v-n-channel-power-mosfet/IRLB8721/productType.html?productType=5546d462533600a401533d494ca36b4f#ispnTab2). If we were to continue using it (seem like an appropriate choice?) it changes your schematic to a GDS pinout. Should we be looking at an alternative component?

A diode is a nice idea.

The 12-5V reg shouldn't have much current going through it? Isn't it solely used to power the ESP and _switch_ the MOSFETs?

We may want to experiment debouncing with an oscilloscope - I tried using 100nF and other values in that range with little success. The only reason I was able to manage the debouncing issue was that I'm fading in/out the LED effect - the fade duration is longer than the debouncing effect. That said, I'd _really_ like to resolve debouncing on this switch but I think it'll be a 2x resistor plus a cap deal...

**Comment by mattytrentini** [comment]
The encoder is labeled "1, 2, 3" but also "A, C, B". Bit confusing! For the record, I'm pulling the middle of the 3 encoding pins to GND.

**Comment by mattytrentini** [comment]
I was toying with the idea of using a Neopixel, mounting it near the rotary encoder, to help with the 'user interface'. It's most compelling when using an RGB strip - I expect that you can press the button six times: on, brightness, red, green, blue, off (maybe normally it's on/off and you have to press and hold to enter the other modes). The Neopixel could help identify the 'mode' that the device is operating in.

What do you think? It'll cost another digital output...

**Comment by mattytrentini** [comment]
Space looks like it'll be an issue; we could connect just one 12V +ve line to the terminal block - assuming current is manageable. I'm measuring about 2A for a 5m (60 LEDs/m for 300 LEDs) strip.

**Comment by HowManyOliversAreThere** [comment]
I'm happy sticking with a TO-220 footprint (and I'll change it to GDS pinout) and then as PCB layout starts we can evaluate whether it makes sense to stick with it or go to a more dense SMT style package (something like SOT-23 if it can get the required current). Just for my records, what sort of current are we looking at pulling through the FETs? (presumably not the IRLB8721's rated 44A)

Can you confirm that diodes will be okay with ~11.5V rather than 12? (I imagine it should be fine but you can never be too careful ;) )

Ah yes sorry reg won't be pulling much, for some reason I keep thinking it's a 5v -> 12v reg and will therefore be powering LEDs...should we try with polulu regulator considered in the design for the moment, and see if we need to bring it on board later? Or just design the reg on board?

Hmm okay, maybe can you do a bit of experimenting with an oscilloscope and some passives and I'll implement based on your findings? Otherwise happy to do it next time we're in the same room and have an oscilloscope handy!

Neopixel as UI seems overly complex, and yet I have no better suggestion at this time that would be both simple and use a single GPIO...I can certainly throw one on there. I'll move D_OUT to D0 (GPIO16) as that doesn't support one-wire according to [this site](https://wiki.wemos.cc/products:d1:d1_mini), and I'll put the neopixel driver pin on D8 (GPIO15). Maybe I could run the other end of the Neopixel out to a terminal block so you could extend a neopixel strip out there if you felt so inclined...this could all become moot when I see how much space I have to work with on the PCB however!

Yeah once I do the initial PCB run we'll see about what sort of optimisations are required...there's a lot of terminal blocks on there at the moment that will have to be reduced / cut out.

**Comment by mattytrentini** [comment]
If we can find a FET in a smaller package that'd be a _huge_ benefit; the TO-220's are massive! As I mentioned above, a 5m strip will pull a couple of amps (not 44 though! :) ).

I'll check if 11.5V is ok...

I like those Pololu regs but if we can find a surface mount 12-5V reg it might be more space-efficient (and cheaper!). Oh, it should work down to at least 5V too - some LED strips operate at 5V and we should support that.

Next time I grab an oscilloscope I'll take some measurements! Hopefully you'll be there. :)

Huh, I can't figure out why D0/GPIO16 is any different...I wonder if that reference is correct?? I can try it when I have some spare time but since you've already worked around it I guess it's a non-issue.

Actually, I did just think of a neater solution - we can use the strips themselves to provide the indication. If it's an RGB strip, briefly 'pop' the brightness on the colour that the mode is changing. If it's a Neopixel strip, same idea but change the colour of all the LEDs briefly to the mode colour. That'll work. Adding an indicator probably isn't necessary then...

**Comment by HowManyOliversAreThere** [comment]
Hmm, it seems we have 2 interesting concepts that I would like to take care of in one fell swoop.

* It would be good to have a small, on board, minimal component voltage regulator solution
* It would be good for the regulator to work down to 5V input so that 5V Led systems can be used

I propose we use a 3V3 LDO and power the Wemos directly through the 3v3 pin. A component such as the [Diodes Inc AZ1117CH-3.3TRG1](https://www.digikey.com.au/product-detail/en/Diodes+Incorporated/AZ1117CH-3.3TRG1/AZ1117CH-3.3TRG1DICT-ND/4505206) should resolve this quite neatly!

Although there may need to be some consideration on the reverse polarity diode if 5v is intended to be used...

**Comment by mattytrentini** [comment]
I'll bow to your better judgement... :)

Basically we can choose - I do note that there's a 5V regulator in the [same package from the same family](https://www.digikey.com.au/product-detail/en/diodes-incorporated/AZ1117EH-5.0TRG1/AZ1117EH-5.0TRG1DIDKR-ND/5001342).

Just for reference, here's the [Wemos schematic](https://wiki.wemos.cc/_media/products:d1:mini_new_v2_2_0.pdf).

**Comment by HowManyOliversAreThere** [comment]
The issue would be that if you have a 5V source voltage, the voltage into the wemos 5V pin would be 5v-dropout, and then the wemos reg will have an input of 5v- drop-out, potentially leading to an under voltage situation on the 3v3 rail, and definitely resulting in 2x regulator inefficiencies, rather than just having the 1x regulator down to 3v3

**Comment by mattytrentini** [comment]
Oh, right, it would mean we'd have to use a buck-boost so our 5V reg could operate lower...

Yep, 3v3 is looking more compelling. 👍

**Comment by HowManyOliversAreThere** [comment]
Trying to find more information on rotary encoders and I discovered the following diagram from [this](https://www.allaboutcircuits.com/projects/how-to-use-a-rotary-encoder-in-a-mcu-based-project/) informative website:

image

This suggests that inline 27k resistors with shunt 100nF caps should resolve our debouncing woes - I think I'll run with this in the design until we have any evidence disproving it (although obviously evidence supporting it would be preferred).

**Comment by mattytrentini** [comment]
I _think_ that the micro should be set to use an internal pull up on the inputs of that design? I haven't done the RC calculation to determine what kind of debounce duration we get with that RC combo...but until we measure it on an oscilloscope it's kinda a guess anyway (switches vary wildly in their debounce pattern apparently).

I read the [classic article on debouncing](http://www.ganssle.com/debouncing.htm) a couple of nights ago - I appreciate the problem a little more but it's frustrating that the issue just hasn't gone away over the years. 

Why haven't micro manufacturers put this stuff on die yet?? Seems like a configurable blob of debounce logic would be straightforward and hugely beneficial. Look at all the different ways people have written software to [work around debouncing](http://hackaday.com/2010/11/09/debounce-code-one-post-to-rule-them-all/)!

Anyway, at least I until I make some measurements with a CRO, I don't have a better solution to offer so yeah, let's go with that design!

**Comment by HowManyOliversAreThere** [comment]
Hey @mattytrentini , can you please confirm the dimensions of your rotary encoder? I've got a generic footprint that I'm running with but a 3D model that doesn't really match it, so it would be nice to confirm footprint size

**Comment by HowManyOliversAreThere** [comment]
As per commit fd3d4ed , there is now a PCB with all components placed. MOSFETs moved from a TO-220 package to SOT23, as they simply would not fit. Critical components options:
* Terminal blocks are 2.54mm pitch
* Regulator is SOT-223 ([Diodes Inc AZ1117CH-3.3TRG1](https://www.digikey.com.au/product-detail/en/Diodes+Incorporated/AZ1117CH-3.3TRG1/AZ1117CH-3.3TRG1DICT-ND/4505206))
* MOSFETs are SOT23 ([Nexperia PMV16XNR](https://www.digikey.com.au/product-detail/en/nexperia-usa-inc/PMV16XNR/1727-2300-1-ND/5395602))
* All resistors and capacitors are 0805
* Diode is SMB or SMC ([Micro Commercial Co SK153-TP](https://www.digikey.com.au/product-detail/en/micro-commercial-co/SK153-TP/SK153-TPCT-ND/1306216))

A lot of these components were selected based on 'heavy use' applications (such as 15A diode), and could be substituted with cheaper, more accessible, more application specific items. Footprints were chosen to be very generic so any available parts could be used for populating the boards.

Placement is ready for initial comments, however obviously pending schematic finalisation, and footprint choice acceptance (more for checking it all fits and how the inputs should be made accessible at this stage).

**Comment by mattytrentini** [comment]
The Rotary Encoder is the same as the one [Adafruit stocks](https://www.adafruit.com/product/377).

[I did just receive a few more from a random AliExpress vendor today and they're larger...]

**Comment by mattytrentini** [comment]
Looks like it all fits! Even with that monstrous diode ;)

I'm running out of _awakedness_ tonight, I've pulled the changes but will have to review them later. Thanks for all your effort!

**Comment by mattytrentini** [comment]
Oh, one thing; I was considering a design that placed the boards in a small box. The idea would be to drill a hole in the top of the box and lock the rotary encoder into the hole - the boards would be fixed below it. However this only gives us about 7-8mm of space on top of the board (top of the PCB to the base of the encoder). We should have 10-11 between our board and the Wemos (depends a little to which side we mount it to). We may have to shuffle the bigger components (terminals) between the boards...

**Comment by HowManyOliversAreThere** [comment]
Ooh, sounds like an intriguing proposition - I'll have to have a further look at the wemos to understand how we can get that to work!

**Comment by mattytrentini** [comment]
Picture something [like this](http://g02.a.alicdn.com/kf/HTB1dlKiLXXXXXXiXXXXq6xXFXXX4/202831103/HTB1dlKiLXXXXXXiXXXXq6xXFXXX4.jpg). But with a rotary encoder on the top shield instead of a micro SD socket. See how there's a gap between the two PCB's? That'll be useful :)

Note that I'm not yet sure which side of the Wemos it would be best to mount our shield to...

**Comment by HowManyOliversAreThere** [comment]
Whichever one gives us the most space in the middle I'm thinking 😉 maybe Esp up like they have?

I think the decision might be quite arbitrary in the end but if we can make a call in the next 24 hours I can do placement again, looking at an encoder on top, terminal blocks on bottom style approach!

Todo: check encoder footprint (I assume we'll go with the Sparkfun sized, smaller encoder?)

**Comment by mattytrentini** [comment]
For the record, none of the Wemos devices I have actually uses an ESP12F module; they all use the Expressif chips directly on-board. I have a mixture of Wemos [D1 mini Pro](https://wiki.wemos.cc/products:d1:d1_mini_pro) and [D1 mini Pro Lite's](https://wiki.wemos.cc/products:d1:d1_mini_lite). Confusingly it's the [D1 mini](https://wiki.wemos.cc/products:d1:d1_mini) that uses the ESP12F. For my boards, the rear is completely bare so it actually gives us more space (albeit not _much_ more, since the chips are all quite low profile). 

So, more space if we attach to the rear. Flip side: from a mounting-in-case point of view it would be _nice_ to have the bare rear of the board _out_ so the electronics is less exposed. So, if we can fit in the space when attaching to the front we should do that; if we need the extra mm or so we can attach to the rear.

That was a lot of words for a simple concept lol. ;)

**Comment by HowManyOliversAreThere** [comment]
Hmm okay, well we are currently using terminal blocks that are 8mm high, so as long as we actually have that 10-11 mm previously quoted, sounds like we should be fine! I agree that bare side of the board down would make the most sense in that case.

**Comment by HowManyOliversAreThere** [comment]
Rotary encoder footprint checked against the [Sparkfun model](https://www.sparkfun.com/products/9117) and found to be correct. 3D model will have to be updated to reflect this size device at some point.

**Comment by mattytrentini** [comment]
If you manage to make a 3D model you could then [submit it back](https://github.com/mcous/kicad-lib/tree/master/footprints)...

**Comment by mattytrentini** [comment]
I'm going to merge this as-is rather than discuss it forever!

**Pull request merged**
